services:
    postgres:
        build:
          context: .
          dockerfile: Dockerfile
        restart: always
        container_name: "postgres_py"
        environment:
          POSTGRES_DB: "postgres"
          POSTGRES_USER: "admin"
          POSTGRES_PASSWORD: "admin123"
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - db-data:/var/lib/postgresql/data
volumes:
  db-data: